// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "actqj71e71udp.h"

/////////////////////////////////////////////////////////////////////////////
// CActqj71e71udp

IMPLEMENT_DYNCREATE(CActqj71e71udp, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CActqj71e71udp properties

/////////////////////////////////////////////////////////////////////////////
// CActqj71e71udp operations
